# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(390, 205)
        AboutDialog.setMinimumSize(QtCore.QSize(390, 205))
        AboutDialog.setMaximumSize(QtCore.QSize(390, 205))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/logo-uartronica-final-mini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutDialog.setWindowIcon(icon)
        AboutDialog.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(AboutDialog)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/images/logo-uartronica-final-mini.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(80, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_app_title = QtWidgets.QLabel(AboutDialog)
        self.label_app_title.setMinimumSize(QtCore.QSize(280, 0))
        self.label_app_title.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_app_title.setObjectName("label_app_title")
        self.verticalLayout_2.addWidget(self.label_app_title)
        self.label_app_version = QtWidgets.QLabel(AboutDialog)
        self.label_app_version.setObjectName("label_app_version")
        self.verticalLayout_2.addWidget(self.label_app_version)
        self.label_released_at = QtWidgets.QLabel(AboutDialog)
        self.label_released_at.setObjectName("label_released_at")
        self.verticalLayout_2.addWidget(self.label_released_at)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_copyright = QtWidgets.QLabel(AboutDialog)
        self.label_copyright.setObjectName("label_copyright")
        self.verticalLayout_2.addWidget(self.label_copyright)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_close = QtWidgets.QPushButton(AboutDialog)
        self.btn_close.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.btn_close, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(AboutDialog)
        self.btn_close.clicked.connect(AboutDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "Sobre Controlo de Produção"))
        self.label_app_title.setText(_translate("AboutDialog", "Controlo de Produção Uploader"))
        self.label_app_version.setText(_translate("AboutDialog", "Versão 2.0"))
        self.label_released_at.setText(_translate("AboutDialog", "Data de lançamento: 25 de abril de 2025"))
        self.label_copyright.setText(_translate("AboutDialog", "Copyright © 2024-2025 Uartrónica"))
        self.btn_close.setText(_translate("AboutDialog", "Fechar"))
import resources_rc
