# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HistoryDialog(object):
    def setupUi(self, HistoryDialog):
        HistoryDialog.setObjectName("HistoryDialog")
        HistoryDialog.resize(756, 399)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/logo-uartronica-final-mini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HistoryDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(HistoryDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(HistoryDialog)
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tree_widget_logs = QtWidgets.QTreeWidget(HistoryDialog)
        self.tree_widget_logs.setAlternatingRowColors(True)
        self.tree_widget_logs.setAllColumnsShowFocus(False)
        self.tree_widget_logs.setWordWrap(False)
        self.tree_widget_logs.setObjectName("tree_widget_logs")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tree_widget_logs.headerItem().setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.tree_widget_logs.headerItem().setForeground(0, brush)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tree_widget_logs.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tree_widget_logs.headerItem().setFont(2, font)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tree_widget_logs.headerItem().setFont(3, font)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tree_widget_logs.headerItem().setFont(4, font)
        self.verticalLayout.addWidget(self.tree_widget_logs)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_previous_page = QtWidgets.QPushButton(HistoryDialog)
        self.btn_previous_page.setObjectName("btn_previous_page")
        self.horizontalLayout_2.addWidget(self.btn_previous_page, 0, QtCore.Qt.AlignRight)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_next_page = QtWidgets.QPushButton(HistoryDialog)
        self.btn_next_page.setObjectName("btn_next_page")
        self.horizontalLayout_2.addWidget(self.btn_next_page, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_close = QtWidgets.QPushButton(HistoryDialog)
        self.btn_close.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(HistoryDialog)
        self.btn_close.clicked.connect(HistoryDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HistoryDialog)

    def retranslateUi(self, HistoryDialog):
        _translate = QtCore.QCoreApplication.translate
        HistoryDialog.setWindowTitle(_translate("HistoryDialog", "Controlo de Produção - Registos"))
        self.label.setText(_translate("HistoryDialog", "Histórico de registos:"))
        self.tree_widget_logs.headerItem().setText(0, _translate("HistoryDialog", "Data de processamento"))
        self.tree_widget_logs.headerItem().setText(1, _translate("HistoryDialog", "Ficheiro"))
        self.tree_widget_logs.headerItem().setText(2, _translate("HistoryDialog", "Localização"))
        self.tree_widget_logs.headerItem().setText(3, _translate("HistoryDialog", "Validação do ficheiro"))
        self.tree_widget_logs.headerItem().setText(4, _translate("HistoryDialog", "Upload"))
        self.btn_previous_page.setText(_translate("HistoryDialog", "<"))
        self.btn_next_page.setText(_translate("HistoryDialog", ">"))
        self.btn_close.setText(_translate("HistoryDialog", "Fechar"))
import resources_rc
