# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log_detail_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogDetailDialog(object):
    def setupUi(self, LogDetailDialog):
        LogDetailDialog.setObjectName("LogDetailDialog")
        LogDetailDialog.setWindowModality(QtCore.Qt.NonModal)
        LogDetailDialog.resize(588, 402)
        LogDetailDialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/logo-uartronica-final-mini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LogDetailDialog.setWindowIcon(icon)
        LogDetailDialog.setToolTip("")
        LogDetailDialog.setWhatsThis("")
        LogDetailDialog.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        LogDetailDialog.setSizeGripEnabled(False)
        LogDetailDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(LogDetailDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(LogDetailDialog)
        self.label.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_timestamp = QtWidgets.QLabel(LogDetailDialog)
        self.label_timestamp.setMinimumSize(QtCore.QSize(0, 0))
        self.label_timestamp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_timestamp.setText("")
        self.label_timestamp.setObjectName("label_timestamp")
        self.verticalLayout_3.addWidget(self.label_timestamp)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(LogDetailDialog)
        self.label_3.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_status = QtWidgets.QLabel(LogDetailDialog)
        self.label_status.setMinimumSize(QtCore.QSize(0, 0))
        self.label_status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.verticalLayout_2.addWidget(self.label_status)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(LogDetailDialog)
        self.label_4.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_logfile = QtWidgets.QLabel(LogDetailDialog)
        self.label_logfile.setMinimumSize(QtCore.QSize(0, 0))
        self.label_logfile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_logfile.setText("")
        self.label_logfile.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_logfile.setObjectName("label_logfile")
        self.horizontalLayout_2.addWidget(self.label_logfile)
        self.btn_log_path = QtWidgets.QToolButton(LogDetailDialog)
        self.btn_log_path.setObjectName("btn_log_path")
        self.horizontalLayout_2.addWidget(self.btn_log_path)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_status_message = QtWidgets.QLabel(LogDetailDialog)
        self.label_status_message.setMinimumSize(QtCore.QSize(0, 100))
        self.label_status_message.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 20pt \"MS Shell Dlg 2\";")
        self.label_status_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_message.setObjectName("label_status_message")
        self.verticalLayout.addWidget(self.label_status_message)
        self.label_edit_log = QtWidgets.QLabel(LogDetailDialog)
        self.label_edit_log.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_edit_log.setObjectName("label_edit_log")
        self.verticalLayout.addWidget(self.label_edit_log)
        self.text_edit_log = QtWidgets.QTextEdit(LogDetailDialog)
        self.text_edit_log.setReadOnly(True)
        self.text_edit_log.setObjectName("text_edit_log")
        self.verticalLayout.addWidget(self.text_edit_log)
        self.line = QtWidgets.QFrame(LogDetailDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.btn_close = QtWidgets.QPushButton(LogDetailDialog)
        self.btn_close.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_close.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.btn_close, 0, QtCore.Qt.AlignRight)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(LogDetailDialog)
        self.btn_close.clicked.connect(LogDetailDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LogDetailDialog)

    def retranslateUi(self, LogDetailDialog):
        _translate = QtCore.QCoreApplication.translate
        LogDetailDialog.setWindowTitle(_translate("LogDetailDialog", "Controlo de Produção - Detalhe"))
        self.label.setText(_translate("LogDetailDialog", "Data de processamento:"))
        self.label_3.setText(_translate("LogDetailDialog", "Estado de carregamento:"))
        self.label_4.setText(_translate("LogDetailDialog", "Ficheiro:"))
        self.btn_log_path.setToolTip(_translate("LogDetailDialog", "Ver localização do ficheiro"))
        self.btn_log_path.setText(_translate("LogDetailDialog", "..."))
        self.label_status_message.setText(_translate("LogDetailDialog", "Erro"))
        self.label_edit_log.setText(_translate("LogDetailDialog", "Detalhes:"))
        self.text_edit_log.setHtml(_translate("LogDetailDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_close.setText(_translate("LogDetailDialog", "Fechar"))
import resources_rc
