# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_product_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectProductDialog(object):
    def setupUi(self, SelectProductDialog):
        SelectProductDialog.setObjectName("SelectProductDialog")
        SelectProductDialog.resize(430, 181)
        SelectProductDialog.setMinimumSize(QtCore.QSize(430, 181))
        SelectProductDialog.setMaximumSize(QtCore.QSize(430, 181))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/logo-uartronica-final-mini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SelectProductDialog.setWindowIcon(icon)
        SelectProductDialog.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectProductDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(SelectProductDialog)
        self.label_2.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, 5, 5, -1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(SelectProductDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.combobox_product = QtWidgets.QComboBox(SelectProductDialog)
        self.combobox_product.setEnabled(True)
        self.combobox_product.setEditable(True)
        self.combobox_product.setObjectName("combobox_product")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combobox_product)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.label_form_error = QtWidgets.QLabel(SelectProductDialog)
        self.label_form_error.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_form_error.setText("")
        self.label_form_error.setObjectName("label_form_error")
        self.verticalLayout.addWidget(self.label_form_error)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.btn_submit = QtWidgets.QPushButton(SelectProductDialog)
        self.btn_submit.setEnabled(True)
        self.btn_submit.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_submit.setObjectName("btn_submit")
        self.verticalLayout.addWidget(self.btn_submit, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(SelectProductDialog)
        QtCore.QMetaObject.connectSlotsByName(SelectProductDialog)

    def retranslateUi(self, SelectProductDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectProductDialog.setWindowTitle(_translate("SelectProductDialog", "Controlo de Produção - Seleciona Produto"))
        self.label_2.setText(_translate("SelectProductDialog", "Selecionar produto"))
        self.label.setText(_translate("SelectProductDialog", "Produto"))
        self.btn_submit.setText(_translate("SelectProductDialog", "Selecionar"))
import resources_rc
