# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_order_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectOrderDialog(object):
    def setupUi(self, SelectOrderDialog):
        SelectOrderDialog.setObjectName("SelectOrderDialog")
        SelectOrderDialog.resize(430, 181)
        SelectOrderDialog.setMinimumSize(QtCore.QSize(430, 181))
        SelectOrderDialog.setMaximumSize(QtCore.QSize(430, 181))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/logo-uartronica-final-mini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SelectOrderDialog.setWindowIcon(icon)
        SelectOrderDialog.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectOrderDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(SelectOrderDialog)
        self.label_2.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, 5, 5, -1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(SelectOrderDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.order_line_edit = QtWidgets.QLineEdit(SelectOrderDialog)
        self.order_line_edit.setObjectName("order_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.order_line_edit)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.label_form_error = QtWidgets.QLabel(SelectOrderDialog)
        self.label_form_error.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_form_error.setText("")
        self.label_form_error.setObjectName("label_form_error")
        self.verticalLayout.addWidget(self.label_form_error)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.btn_submit = QtWidgets.QPushButton(SelectOrderDialog)
        self.btn_submit.setEnabled(True)
        self.btn_submit.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_submit.setObjectName("btn_submit")
        self.verticalLayout.addWidget(self.btn_submit, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(SelectOrderDialog)
        QtCore.QMetaObject.connectSlotsByName(SelectOrderDialog)

    def retranslateUi(self, SelectOrderDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectOrderDialog.setWindowTitle(_translate("SelectOrderDialog", "Controlo de Produção - Seleciona Produto"))
        self.label_2.setText(_translate("SelectOrderDialog", "Selecionar ordem de fabrico"))
        self.label.setText(_translate("SelectOrderDialog", "Ordem"))
        self.btn_submit.setText(_translate("SelectOrderDialog", "Selecionar"))
import resources_rc
