# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_workstation_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectWorkstationDialog(object):
    def setupUi(self, SelectWorkstationDialog):
        SelectWorkstationDialog.setObjectName("SelectWorkstationDialog")
        SelectWorkstationDialog.resize(430, 181)
        SelectWorkstationDialog.setMinimumSize(QtCore.QSize(430, 181))
        SelectWorkstationDialog.setMaximumSize(QtCore.QSize(430, 181))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/logo-uartronica-final-mini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SelectWorkstationDialog.setWindowIcon(icon)
        SelectWorkstationDialog.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectWorkstationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(SelectWorkstationDialog)
        self.label_2.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, 5, 5, -1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(SelectWorkstationDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.combobox_workstation = QtWidgets.QComboBox(SelectWorkstationDialog)
        self.combobox_workstation.setEnabled(True)
        self.combobox_workstation.setEditable(True)
        self.combobox_workstation.setObjectName("combobox_workstation")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combobox_workstation)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.label_form_error = QtWidgets.QLabel(SelectWorkstationDialog)
        self.label_form_error.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_form_error.setText("")
        self.label_form_error.setObjectName("label_form_error")
        self.verticalLayout.addWidget(self.label_form_error)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.btn_submit = QtWidgets.QPushButton(SelectWorkstationDialog)
        self.btn_submit.setEnabled(True)
        self.btn_submit.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_submit.setObjectName("btn_submit")
        self.verticalLayout.addWidget(self.btn_submit, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(SelectWorkstationDialog)
        QtCore.QMetaObject.connectSlotsByName(SelectWorkstationDialog)

    def retranslateUi(self, SelectWorkstationDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectWorkstationDialog.setWindowTitle(_translate("SelectWorkstationDialog", "Controlo de Produção - Selecionar Posto"))
        self.label_2.setText(_translate("SelectWorkstationDialog", "Selecionar posto"))
        self.label.setText(_translate("SelectWorkstationDialog", "Posto"))
        self.btn_submit.setText(_translate("SelectWorkstationDialog", "Selecionar"))
import resources_rc
